**Imports and Setup**

In [1]:
import os
import dotenv
import pandas as pd
import duckdb

# setup
API_KEY = dotenv.get_key("./.env", "api_min")

# API root entry point
URL = "https://api.mindat.org"

# authorization header that must be included with each request.
headers = {'Authorization': 'Token ' + API_KEY}

# directories
DATA_DIR = os.path.join(os.path.abspath('./'), 'data')
QUERIES_DIR = os.path.join(os.path.abspath('./'), 'queries')

# fixing pandas analyzer
duckdb.execute("SET GLOBAL pandas_analyze_sample = 100_000")

pd.set_option('display.max_columns', None)

In [70]:
silver_geomaterials = duckdb.read_csv(os.path.join(DATA_DIR,'silver_geomaterials.csv'))

In [71]:
with open(os.path.join(QUERIES_DIR,'silver_minerals_hand.sql')) as f:
    query_nb = f.read()
    f.close()            

# duckdb.sql(query_nb).show(max_width=10000, max_rows=100)

duckdb.sql(query_nb).to_df().head(100)

,idGeomaterial,idGroup,descName,descMindatFormula,descElements,descKeyElements,descEntryTypeText,vlDiscoveryYear,vlWeighting,descDiapheny,descCleavage,descParting,descTenacity,descColour,descLustreType,descStreak,descDescriptionShort,descCleavageType,descFractureType,descMorphology,descTwinning,dtUpdatedTime
0,471274,0,Microspar,None,None,None,mineral,NaN,0,None,None,None,None,None,None,None,a descriptive term for finely crystalline (gra...,None,None,None,None,2024-09-10 21:45:39
1,53071,0,"""Tear-Pants"" Rock",None,None,None,mineral,NaN,0,None,None,None,None,None,None,None,a field term for a partly silicified carbonate...,None,None,None,None,2018-08-19 18:55:26
2,470852,0,'Unnamed (Cu-Mg-Silicate)',None,None,None,mineral,1981.0,0,None,None,None,None,None,None,None,in the x-ray diffraction pattern the lines of ...,None,None,None,None,2023-08-21 20:11:26
3,54217,0,'Unnamed (Monoclinic Phase-II Cristobalite)',SiO2,"'Si', 'O'",None,mineral,NaN,0,None,None,None,None,None,None,None,"a synthetic, high-pressure phase (not a minera...",None,None,None,None,2020-01-16 13:48:31
4,29206,0,10 Å Phase,"Mg, Si, O, H","'Mg', 'Si', 'O', 'H'",None,mineral,NaN,0,None,None,None,None,None,None,None,a phase in the series of dense hydrous magnesi...,None,None,None,None,2011-07-07 12:47:37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,71,39941,Akhtenskite,&#949;-Mn4+O2,"'Mn', 'O'",None,mineral,NaN,44,opaque,on {001},None,None,light grey to black,None,black,None,distinct/good,None,"as microscopic crystals, flaky to platy on {00...",None,2022-03-16 18:34:26
96,6794,29299,Akimotoite,"(Mg,Fe2+)SiO3","'Fe', 'Mg', 'Si', 'O'",None,mineral,NaN,13,None,None,None,None,colourless,vitreous,white,None,None,None,None,None,2022-10-30 11:02:18
97,42244,0,Aklimaite,Ca4[Si2O5(OH)2](OH)4&middot;5H2O,"'Ca', 'Si', 'O', 'H'",None,mineral,NaN,1,transparent,{001},None,brittle,colorless or light-pinkish,vitreous,white,None,perfect,None,type material crystals are columnar or lath-sh...,None,2023-12-31 08:09:21
98,53220,43290,Akopovaite,Al4Li2(OH)12(CO3)(H2O)3,"'Al', 'Li', 'O', 'C', 'H'",'Li',mineral,NaN,6,None,{001},None,None,white or yellowish,silky,None,None,perfect,None,None,None,2024-04-12 09:42:11
99,72,470609,Akrochordite,MnMn2Mn2(AsO4)2(OH)4(H2O)4,"'As', 'Mn', 'O', 'H'",'As',mineral,1915.0,36,translucent,"on <mi>{010}</mi> , perfect; a second, perpend...",None,brittle,"yellowish red-brown, pale to dark brown, pale ...","sub-vitreous,resinous,dull",None,None,perfect,None,"crystals are prismatic to lathlike, elongated ...",None,2024-05-08 17:19:17

In [36]:
query_nb = """

    select
        *
    from silver_geomaterials
    where descEntryTypeText = 'mineral' and descOpticalType is not null and descName = 'Kurgantaite'
         
    --group by 1 
    --order by 2 desc
    limit 100

"""

duckdb.sql(query_nb).to_df()

,idGeomaterial,idLongId,idGUID,descName,descNameCorrected,dtUpdatedTime,descMindatFormula,descMindatFormulaNote,descImaFormula,descImaStatus,descImaNotes,idVarietOf,idSyn,idPolyTypeOf,idGroup,idEntryType,descEntryTypeText,descDescriptionShort,descImpurities,descElements,descSigElements,descTlForm,idCIM,descOccurrence,descOtherOccurrence,descIndustrial,vlDiscoveryYear,descDiapheny,descCleavage,descParting,descTenacity,descColour,vlCsMetamict,descOpticalExtinction,vlHMin,vlHardType,vlHmax,vlVhnMin,vlVhnMax,vlVhnerror,vlVhng,vlVhns,descLuminescence,descLustre,descLustreType,descAboutName,descOtherDescription,descStreak,descCSystem,vlCClass,vlSpaceGroup,vlA,vlB,VlC,vlAlpha,vlBeta,vlGamma,vlAError,vlBError,vlCError,vlAlphaError,vlBetaError,vlGammaError,vlVa3,vlZ,vlDMeas,vlDMeas2,vlDCalc,vlDMeasError,vlDCalcError,descCleavageType,descFraactureType,descMorphology,descTwinning,descEpitaxDescription,descOpticalType,descOpticalSign,vlOpticalAlpha,vlOpticalBeta,vlOpticalGamma,vlOpticalOmega,vlOpticalEpsilon,vlOpticalAlpha2,vlOpticalBeta2,vlOpticalGamma2,vlOpticalEpsilon2,vlOpticalOmega2,vlOpticalLn,vlOpticalLn2,vlOptical2VCalc,vlOptical2VMeasured,vlOptical2VCalc2,vlOptical2VMeasured2,vlOpticalAlphaError,vlOpticalBetaError,vlOpticalGammaError,vlOpticalOmegaError,vlOpticalEpsilonError,vlOpticalNError,vlOptical2VCaclError,vlOptical2VMeasuredError,descOpticalDispersion,descOpticalPleaochroism,descOpticalPleochroismDescription,descOpticalBirefringence,descOpticalComments,descOpticalColour,descOpticalInternal,descOpticalTropic,descOpticalAnisotropism,descOpticalBireflectance,descOpticalR,descUV,descIR,descMagnetism,descTypeSpecimenStore,descCommentHardness,descStrunz10ed1,descStrunz10ed2,descStrunz10ed3,descStrunz10ed4,descDana8ed1,descDana8ed2,descDana8ed3,descDama8ed4,descThermalBehaviour,descCommentLuster,descCommentBreak,descCommentDense,descCommentCrystal,descCommentColor,descElectrical,descTranglide,flNoLocAdd,descSpecDispm,descSpaceGroupSet,vlApprovalYear,vlPublicationyear,descImaHistory,idRockParent,idRockParent2,flRockRoot,descRockBgsCode,descMeteoriticalCode,descKeyElements,descShortcodeIma,vlRiMin,vlRiMax,vlWeighting
0,8212,1:1:8212:5,6427fb83-c41b-4427-99c2-3150d7e18481,Kurgantaite,Kurgantaite,2023-01-19 10:46:59,CaSr[B<sub>5</sub>O<sub>9</sub>]Cl&middot;H<su...,None,CaSrB<sub>5</sub>O<sub>9</sub>Cl &middot; H<su...,"[APPROVED, GRANDFATHERED]",[],0,0,0,39748,0,mineral,None,None,"['Ca', 'Cl', 'Sr', 'B', 'O', 'H']","['Ca', 'Cl', 'Sr', 'B', 'O', 'H']",Fine-grained nodules up to 4 cm across.,None,In a borate deposit.,None,None,1952,Transparent,None,None,brittle,Colourless to white,0,None,6.0,3,6.5,0,0,0,0,0,None,None,Vitreous,"Named for the type locality, Kargan-tau, Kazak...",None,White,Triclinic,1,1,6.573,6.445,6.369,60.995,61.257,77.191,0,0,0,0,0,0,206.9,1,2.99,2.99,3.04,0,0,Imperfect/Fair,Irregular/Uneven,None,None,None,Biaxial,+,1.637,1.638,1.675,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,19.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,None,Non-pleochroic,None,None,None,None,None,None,None,None,None,None,None,None,"A. E. Fersman Mineralogical Museum, Moscow, Ru...",None,6,E,D,05,0,0,0,0,None,None,None,None,None,None,None,None,0,None,0,2002,1952,IMA Code 00-B - Kurgantaite revalidated (2002).,0,0,0,None,None,"['B', 'Cl', 'Sr']",Kga,NaN,NaN,17